// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type ModificarApellido struct {
	Apellido string `json:"apellido"`
}

type ModificarCorreo struct {
	Correo string `json:"correo"`
}

type ModificarNombre struct {
	Nombre string `json:"nombre"`
}

type ModificarUserName struct {
	Username string `json:"username"`
}

type Mutation struct {
}

type NewUserInput struct {
	Username string `json:"username"`
	Nombre   string `json:"nombre"`
	Apellido string `json:"apellido"`
	Correo   string `json:"correo"`
	Telefono string `json:"telefono"`
	Rol      string `json:"rol"`
	Edad     int    `json:"edad"`
	Password string `json:"password"`
}

type Query struct {
}

type User struct {
	ID       string `json:"id"`
	Nombre   string `json:"nombre"`
	Apellido string `json:"apellido"`
	Username string `json:"username"`
	Correo   string `json:"correo"`
	Telefono string `json:"telefono"`
	Rol      string `json:"rol"`
	Edad     int    `json:"edad"`
}
