// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AgregarProductoInput struct {
	IDUsuario  string `json:"IDUsuario"`
	IDProducto string `json:"IDProducto"`
}

type Carrito struct {
	ID          string   `json:"id"`
	IDUsuario   string   `json:"idUsuario"`
	IDProductos []string `json:"idProductos"`
}

type EliminarProductoInput struct {
	IDUsuario  string `json:"IDUsuario"`
	IDProducto string `json:"IDProducto"`
}

type Mutation struct {
}

type Query struct {
}
